[project]
name = "ComfyUI-Studio-Fury"
description = "Nodos custom, al estilo fury, nodos que aÃ±aden versatilidad. con el tiempo ira creciendo los nodos."
version = { file = "VERSION" }
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/FuryNocturn/ComfyUI-Studio-Fury"

[tool.comfy]
PublisherId = "FuryNocturnTV"
DisplayName = "ComfyUI-Studio-Fury"
Icon = "ðŸ§©"
